In [1]:
import numpy as np
A = np.array([[-2, -3],
             [1, 0]])
B = np.array([[1, 1], 
             [1, 0]])
x = np.array([[-1],
             [1]])


In [2]:
#Computer C = A^-1
C = np.linalg.inv(A)
print("C: \n", np.matrix.round(C, 3))

# Check AC = I and CA = I ie, AC = CA
AC = np.dot(A,C)
CA = np.dot(C,A)

if np.array_equal(AC,CA):
    print("\nEUREKA!")

# Compute Ax
Ax = np.dot(A,x)
print("\nAx: \n",Ax)

# Compute A^T A
AT = A.transpose()
ATA = np.dot(AT,A)
print("\nA^T *A: \n", ATA)

# Compute Ax - Bx
Bx = np.dot(B,x)
D = Ax - Bx
print("\nAx-Bx: \n", D)

# Compute ||x|| Use dot Product
# sqrt(x*x)
x_vec_norm = np.sqrt(np.dot(x.transpose(),x))
print("\n||x||: ", x_vec_norm) # w/ sqrt

# Compute ||Ax-Bx|| 
D_vec_norm = np.sqrt(np.dot(D.transpose(), D))
print("\n||Ax-Bx||: ", D_vec_norm) # w/ sqrt

# Print first column of A, no for loop
print("\nFirst Column A: \n", A[:,0])

# Assign the vector x to the first column of B (do not use a loop – use “array slicing” instead)
B[:,0] = x[:,0]
print("\nB column w/x: \n", B)

# Compute the element-wise product between the first column of A and the second column of A
A_prod = A[:, 0]*A[:, 1]
print("A Product: ", A_prod)


C: 
 [[-0.     1.   ]
 [-0.333 -0.667]]

Ax: 
 [[-1]
 [-1]]

A^T *A: 
 [[5 6]
 [6 9]]

Ax-Bx: 
 [[-1]
 [ 0]]

||x||:  [[1.41421356]]

||Ax-Bx||:  [[1.]]

First Column A: 
 [-2  1]

B column w/x: 
 [[-1  1]
 [ 1  0]]
A Product:  [6 0]
